on:
  deployment_status:

name: Publish GraphQL Schema

jobs:
  publish-subgraph:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      APOLLO_VCS_COMMIT: ${{ github.sha }}
      BASE_URL: ${{ github.event.deployment_status.target_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.18.1 | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - name: Running Rover introspect and publish
        run: |
          rover subgraph introspect ${{ env.BASE_URL }}/api/graphql | rover subgraph publish abdulachik-blog@current --name blog --schema - --routing-url https://www.abdulachik.dev/api/graphql
