on:
  deployment_status:

name: Publish GraphQL Schema

jobs:
  publish:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      APOLLO_VCS_COMMIT: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.18.1 | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - run: bun publish-graph

